
export const catalago = [
    { 
        id: 1, 
        marca: 'Zara', 
        nome: 'Camisa Larga com Bolsos', 
        preco: 70, 
        imagem: 'product-1.jpg', 
        feminino: false, 
    }, 
    { 
        id: 2,
        marca: 'Zara',
        nome: 'Casaco Reto com Lã', 
        preco: 85, 
        imagem: 'product-2.jpg', 
        feminino: true, 
    }, 
    { 
        id: 3, 
        marca: 'Zara', 
        nome: 'Jaqueta com Efeito Camurça', 
        preco: 60, 
        imagem: 'product-3.jpg', 
        feminino: false, 
    },
    { 
        id: 4, 
        marca: 'Zara', 
        nome: 'Sobretudo em Mescla de Lã', 
        preco: 160, 
        imagem: 'product-4.jpg', 
        feminino: false, 
    },
    { 
        id: 5, 
        marca: 'Zara', 
        nome: 'Camisa Larga Acolchoada de Veludo Cotelê', 
        preco: 110, 
        imagem: 'product-5.jpg', 
        feminino: false, 
    }, 
    { 
        id: 6, 
        marca: 'Zara', 
        nome: 'Casaco de Lã com Botões', 
        preco: 170, 
        imagem: 'product-6.jpg', 
        feminino: true, 
    }, 
    { 
        id: 7, 
        marca: 'Zara', 
        nome: 'Casaco com Botões', 
        preco: 75, 
        imagem: 'product-7.jpg', 
        feminino: true, 
    }, 
    { 
        id: 8, 
        marca: 'Zara', 
        nome: 'Colete Comprido com Cinto', 
        preco: 88, 
        imagem: 'product-8.jpg', 
        feminino: true, 
    },
    { 
        id: 9, 
        marca: 'Zara', 
        nome: 'Calça com bolso ultility', 
        preco: 90, 
        imagem: 'product-9.jpg', 
        feminino: false, 
    }, 
    { 
        id: 10,
        marca: 'Zara',
        nome: 'Colete Ultility', 
        preco: 105, 
        imagem: 'product-10.jpg', 
        feminino: true, 
    }, 
    { 
        id: 11, 
        marca: 'Zara', 
        nome: 'Moletom Crew Neck', 
        preco: 83, 
        imagem: 'product-11.jpg', 
        feminino: false, 
    },
    { 
        id: 12, 
        marca: 'Zara', 
        nome: 'Camiseta Tecnica furada com Detalhes', 
        preco: 160, 
        imagem: 'product-12.jpg', 
        feminino: false, 
    },
    { 
        id: 13, 
        marca: 'Zara', 
        nome: 'Jeans TRF reto hight waist regular Length', 
        preco: 111, 
        imagem: 'product-13.jpg', 
        feminino: true, 
    }, 
    { 
        id: 14, 
        marca: 'Zara', 
        nome: 'Jeans TRF reto com cintura alta', 
        preco: 120, 
        imagem: 'product-14.jpg', 
        feminino: true, 
    }, 
];